{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nacos-operator.serviceAccountName" . }}
  labels:
    {{- include "nacos-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.rbac.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nacos-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["nacos.io"]
    resources: ["nacos"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["nacos.io"]
    resources: ["nacos/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [""]
    resources: ["configmaps","pods","services","events","secrets"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nacos-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nacos-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nacos-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nacos-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nacos-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nacos-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nacos-operator.fullname" . }}
rules:
  - apiGroups:
      - nacos.io
    resources:
      - nacos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nacos.io
    resources:
      - nacos/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
    resources:
      - configmaps
      - statefulsets
      - pods
      - services
      - events
      - jobs
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch

{{- end }}

{{- end }}
